//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ماشین.
        /// </summary>
        public static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبدا.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ورود.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فی کمیسیون.
        /// </summary>
        public static string CommissionAmount {
            get {
                return ResourceManager.GetString("CommissionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن مقصد.
        /// </summary>
        public static string DestinationWeight {
            get {
                return ResourceManager.GetString("DestinationWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن خالی.
        /// </summary>
        public static string EmptyWeight {
            get {
                return ResourceManager.GetString("EmptyWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن پر.
        /// </summary>
        public static string FullWeight {
            get {
                return ResourceManager.GetString("FullWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ورود.
        /// </summary>
        public static string InputDate {
            get {
                return ResourceManager.GetString("InputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string InputDesc {
            get {
                return ResourceManager.GetString("InputDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت ورود.
        /// </summary>
        public static string InputTime {
            get {
                return ResourceManager.GetString("InputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه متفرقه.
        /// </summary>
        public static string OtherAmount {
            get {
                return ResourceManager.GetString("OtherAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پس کرایه.
        /// </summary>
        public static string PostRentAmount {
            get {
                return ResourceManager.GetString("PostRentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن مبدا.
        /// </summary>
        public static string SourceWeight {
            get {
                return ResourceManager.GetString("SourceWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره بارنامه.
        /// </summary>
        public static string TransporterCode {
            get {
                return ResourceManager.GetString("TransporterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه باسکول.
        /// </summary>
        public static string WeighbridgeAmount {
            get {
                return ResourceManager.GetString("WeighbridgeAmount", resourceCulture);
            }
        }
    }
}
